### ISSUE TITLE
Issue in WaitingForPlayersEvent

### ISSUE THREAD

**Issue by ITeMbI4** [Cyanox62/BetterDisarming#3]
![image](https://user-images.githubusercontent.com/46756889/59228835-7f3b3580-8be1-11e9-9d43-8c0ae447b93c.png)

**Comment by Cyanox62** [comment]
Was the round force restarted or did the round end screen come up and restart naturally?

**Comment by ITeMbI4** [comment]
It comes up when server started/restarted, it doesn't appear when round restarted
![image](https://user-images.githubusercontent.com/46756889/59230924-c0cedf00-8be7-11e9-977b-4c4db73af434.png)

**Comment by Cyanox62** [comment]
If a player connects before the server fully starts up it will restart the round automatically, that's why it says  `Sending request to SCP: Secret Laboratory`. Anyways I'll put out a hotfix for this in a few minutes.
